### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by jpmirandaa** [dualcube/moodle-theme_rocket#2]
Last version Rocket Theme 2.7 (Build: 20140823) (2014091804) on Moodle 3.1.10
When entering the main page through the URL on browser, only shows the login page persistantly including when 'homepage' is "site" selected and 'forcelogin' is unchecked.
If this is not an issue, please tell me how to solve this.
Thanks and regards.

**Comment by parthajeet** [comment]
Hello,

We have updated the theme. Please download the latest version from moodle.org.

Regards,
Parthajeet~
